boaslibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('library.urls'), name='library_urls'),
    path('accounts/', include('allauth.urls')),
]

library/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.BookList.as_view(), name='home'),
    path('<slug:slug>/', views.BookDetail.as_view(), name='book_detail'),
    path('like/<slug:slug>', views.BookList.as_view(), name='book_like'),
]

library/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from datetime import date
import uuid


class Book(models.Model):
    # Model representing a book
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="library_books")
    cover_image = CloudinaryField('image', default='placeholder')
    summary = models.TextField(help_text='Enter a brief description of the book', blank=True)
    uploaded_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='librarybook_like', blank=True)

    class Meta:
        ordering = ["-uploaded_on"]

    def __str__(self):
        # String for representing the Model Object
        return self.title

    def number_of_likes(self):
        # Returns the number of likes on a book
        return self.likes.count()

    def get_absolute_url(self):
        # Returns the URL to access a detail record for this book.
        return reverse('book-detail', args=[str(self.id)])


class Review(models.Model):
    # Model Representing the reviews on a book
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="reviews")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    uploaded_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["uploaded_on"]

    def __str__(self):
        # String for representing the Model Object
        return f"Reviews {self.body} by {self.name}"


class BookInstance(models.Model):
    # Model representing a specific book that can be borrowed from the library.
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        # String for representing the Model object.
        return '{0} ({1})'.format(self.id, self.book.title)

library/forms.py
from .models import Review
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('body',)

library/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic, View
from django.http import HttpResponseRedirect
from .forms import ReviewForm


# Create your views here.

from .models import Book, BookInstance


def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Available copies of books
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits+1

    # Render the HTML template index.html with the data in the context variable.
    return render(
        request,
        'index.html',
        context={'num_books': num_books, 'num_instances': num_instances,
                 'num_instances_available': num_instances_available,
                 'num_visits': num_visits},
    )


class BookList(generic.ListView):
    model = Book
    queryset = Book.objects.all().order_by('-uploaded_on')
    template_name = 'index.html'
    paginate_by = 6


class BookDetail(View):
    def get(self, request, slug, *args, **kwargs):
        queryset = Book.objects.filter()
        book = get_object_or_404(queryset, slug=slug)
        reviews = book.reviews.filter(approved=True).order_by('uploaded_on')
        liked = False
        if book.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "book_detail.html",
            {
                "book": book,
                "reviews": reviews,
                "reviewed": False,
                "liked": liked,
                "review_form": ReviewForm,
            },
        )

    def post(self, request, slug, *args, **kwargs):

        queryset = Book.objects.filter()
        book = get_object_or_404(queryset, slug=slug)
        reviews = book.reviews.filter().order_by("-uploaded_on")
        liked = False
        if book.likes.filter(id=self.request.user.id).exists():
            liked = True

        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            review_form.instance.email = request.user.email
            review_form.instance.name = request.user.username
            review = review_form.save(commit=False)
            review.book = book
            review.save()
        else:
            review_form = ReviewForm()

        return render(
            request,
            "book_detail.html",
            {
                "book": book,
                "reviews": reviews,
                "reviewed": True,
                "review_form": review_form,
                "liked": liked
            },
        )


class BookLike(View): 
    def post(self, request, slug, *args, **kwargs):
        book = get_object_or_404(Book, slug=slug)
        if book.likes.filter(id=request.user.id).exists():
            book.likes.remove(request.user)
        else:
            book.likes.add(request.user)

        return HttpResponseRedirect(reverse('book_detail', args=[slug]))

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>The BOAs-Kids Library</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">boas<span
                        class="thin">|Library</span></span></span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    readers are leaders
                </span>
            </div>
        </div>
    </nav>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Powered by K-BOAs Librarians</p>
        <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i></p>
    </footer>    
</body>

</html>

templates/book_detail.html
{% extends 'base.html' %} 

{% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Book title goes in these h1 tags -->
                <h1 class="book-title">{{ book.title }}</h1>
                <!-- Book author goes before the | the book's uploaded date goes after -->
                <p class="book-subtitle">{{ book.author }} | {{ book.uploaded_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The cover image URL goes in the src attribute -->
                {% if "placeholder" in book.cover_image.url %}
                <img src="{{ book.cover_image.url }}" width="100%">
                {% else %}
                <img src="{{ book.cover_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The book summary goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <div class="card-text">
                    {{ book.summary | safe }}
                </div>
            
                <div class="row">

                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'book_like' book.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}

                                <button type="submit" name="book_id" value="{{book.slug}}" class="btn-like"><i 
                                    class="fas fa-heart"></i></button>

                                {% else %}

                                <button type="submit" name="book_id" value="{{book.slug}}" class="btn-like"><i 
                                    class="far fa-heart"></i></button>

                                {% endif %}
                            </form>
                            {% else %}

                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                            <span class="text-secondary">{{ book.number_of_likes }} </span>
                        </strong>
                    </div>
                    
                    <div class="col-1">
                        {% with reviews.count as total_reviews %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_reviews variable goes before the closing strong tag -->
                            {{ total_reviews }}
                        </strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Reviews:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the tags to iterate through each review in reviews -->
                {% for review in reviews %}
                <div class="reviewss" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The reviewer's name goes here. Check the model if you're not sure what that is -->
                        {{ review.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The review's uploaded date goes here -->
                            {{ review.uploaded_on}}
                        </span> wrote:
                    </p>
                    <!-- The body of the review goes before the | -->
                    {{  review.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->
                {% if reviewed %}
                <div class="alert alert-success" role="alert">
                    Your review has been posted.
                </div>
                {% else %}
                {% if user.is_authenticated %}

                <h3>Leave a review:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ review_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/bookinstance_list_borrowed_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book_detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">

    <div class="row">

        <!-- Library Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for book in book_list %}
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="image-container">
                                    {% if "placeholder" in book.cover_image.url %}
                                    <img class="card-img-top"
                                        src="">
                                    {% else %}
                                    <img class="card-img-top" src=" {{ book.cover_image.url }}">
                                    {% endif %}
                                    <div class="image-flash">
                                        <p class="author">Author: {{ book.author }}</p>
                                    </div>
                                </div>
                                <a href="{% url 'book_detail' book.slug %}" class="book-link">
                                    <h2 class="card-title">{{ book.title }}</h2>
                                    <div class="card-text">{{ book.summary | safe }}</div>
                                </a>
                                <hr />
                                <p class="card-text text-muted h6">{{ book.uploaded_on }} <i
                                        class="far fa-heart"></i>{{ book.number_of_likes }}</p> 

                            </div>
                        </div>
                    </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{%endblock%}